apiVersion: idp.rottler.io/v1alpha1
kind: ApplicationEnvironment
metadata:
  name: team-a-test-test-8
  labels:
    idp.rottler.io/team: team-a
    idp.rottler.io/system: test
    idp.rottler.io/component: test-8
spec:
  team: team-a
  system: test
  component: test-8
