apiVersion: idp.rottler.io/v1alpha1
kind: ApplicationEnvironment
metadata:
  name: team-a-demo-test-spa
  annotations:
    # Ensure ApplicationEnvironment is deleted before ArgoCD project
    argocd.argoproj.io/sync-wave: "1"
  labels:
    idp.rottler.io/team: team-a
    idp.rottler.io/system: demo
    idp.rottler.io/component: test-spa
spec:
  team: team-a
  system: demo
  component: test-spa
