apiVersion: idp.rottler.io/v1alpha1
kind: ApplicationEnvironment
metadata:
  name: team-a-test-maps-api
  labels:
    idp.rottler.io/team: team-a
    idp.rottler.io/system: test
    idp.rottler.io/component: maps-api
spec:
  team: team-a
  system: test
  component: maps-api
